### ISSUE TITLE
Supplementary oscmulticast.mxo

### ISSUE THREAD

**Issue by dandrewstewart** [malloch/mapper-max-pd#4]
oscmulticast.mxo in the old_bindings directory wasn’t updated with version “1.2.3”, I think.  Can this MXO be removed, seeing how it’s a supplementary, unnecessary, oscmulticast.mxo?  The functioning, updated, oscmulticast.mxo is in the oscmulticast directory.

**Comment by malloch** [comment]
The version in the old_bindings directory of release 1.2.2 wasn't updated to include liblo in the .mxo bundle. This has been fixed now in the release .zip and I will modify the packaging script.
