### ISSUE TITLE
Max Multi-User Crashes

### ISSUE THREAD

**Issue by kaseypocius** [malloch/mapper-max-pd#9]
Max crash on one devices causes max to crash across all devices currently connected to the network.
[200122_CrashLog.txt](https://github.com/malloch/mapper-max-pd/files/4100914/200122_CrashLog.txt)

**Comment by malloch** [comment]
Hi @kaseypocius – could you describe the situation a bit more? Version of libmapper (printed in the Max console on startup), which objects you were using (mapper or map.in/map.out etc), and whether Max had "overdrive" enabled? By "all devices currently connected" do you mean there were active maps between these devices and the crashed device? Thanks!

**Comment by kaseypocius** [comment]
I'm on v0.8.1 beta , using the map.device with map.in/map.out objs, overdrive enabled. There is an active map between one device and the other 4 sound making laptops on the network, but all laptops seems to go at the same time, so it's hard to say which device is the route of the problem.

**Comment by malloch** [comment]
I will definitely look into this strange behaviour! That said, overdrive does not play well with external objects in general, and the mapper objects in particular.

**Comment by kaseypocius** [comment]
I'll try it with overdrive off, though this crash doesn't seem to manifest when I'm working at home even after hours of use (same switch & AP combo as we use for rehearsals). I'll let you know if I get more clarity on this bug, it might be related to something higher up in the Concordia network tree, rather than our laptops.

**Comment by kaseypocius** [comment]
Not overdrive! but the crashes are less frequent with it off. I'll let you know if we discover more during the rehearsal today, running the network on a different concordia network structure for the rehearsal & concert today

**Comment by malloch** [comment]
I just released [Version 1.2.4](https://github.com/malloch/mapper-max-pd/releases/tag/1.2.4) – can you check whether this fixes your crash? Thanks!

**Comment by kaseypocius** [comment]
Hey, we've updated and had 2 full rehearsals now crash free. I'll wait to close this once i've had a chance of forcing a Max crash and checking if the collective crashing is still an issue. There are some new issues that occur with the GUI on webmapper, but only one member experiences this on his Macbook Air. I'll try and get him in touch with you/more info soon. Thanks a million!

**Comment by kaseypocius** [comment]
Hey Joe, we had a crash last night with one user, and everyone else's Max stayed online. We've had some other bugs, but they were isolated to individual users. They should all be in contact with you directly soon. Thanks a million!
